// Auto-generated by krust-sitter — do not edit
(function () {
  var patterns = [
    { regex: /\/\/.*$/gm, cls: 'wit-comment' },
    { regex: /\/\*[\s\S]*?\*\//g, cls: 'wit-comment' },
    { regex: /"[^"]*"/g, cls: 'wit-string' },
    { regex: /@|@since|@unstable|@deprecated|@test/g, cls: 'wit-decorator' },
    { regex: /(?<![a-zA-Z0-9_-])(?:package|use|as|version|feature|interface|record|variant|enum|flags|type|resource|constructor|static|func|bool|char|string|list|option|result|tuple|future|stream|async|let|shared|return|break|continue|true|false|assert|await|if|else|while|for|in|to|downto|step|simd|match|_|map|filter|reduce|some|none|ok|err|atomic|load|store|add|sub|cmpxchg|wait|notify|spawn|thread|join|world|import|export|include)(?![a-zA-Z0-9_-])/g, cls: 'wit-keyword' },
    { regex: /[0-9]+/g, cls: 'wit-number' },
  ];

  function escapeHtml(t) {
    return t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  }

  function highlight(code) {
    var matches = [];
    for (var i = 0; i < patterns.length; i++) {
      var p = patterns[i];
      p.regex.lastIndex = 0;
      var m;
      while ((m = p.regex.exec(code)) !== null) {
        matches.push({ s: m.index, e: m.index + m[0].length, t: m[0], c: p.cls });
      }
    }
    matches.sort(function (a, b) { return a.s - b.s || b.e - a.e; });
    var result = '', cursor = 0;
    for (var i = 0; i < matches.length; i++) {
      var m = matches[i];
      if (m.s < cursor) continue;
      if (m.s > cursor) result += escapeHtml(code.slice(cursor, m.s));
      result += '<span class="' + m.c + '">' + escapeHtml(m.t) + '</span>';
      cursor = m.e;
    }
    if (cursor < code.length) result += escapeHtml(code.slice(cursor));
    return result;
  }

  function run() {
    document.querySelectorAll('code.language-wit').forEach(function (b) {
      if (b.dataset.witHl) return;
      b.innerHTML = highlight(b.textContent);
      b.dataset.witHl = '1';
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', run);
  } else {
    run();
  }
  new MutationObserver(run).observe(document.body, { childList: true, subtree: true });
})();
