//! Build script for kettu-cli.
//!
//! Walks `../../docs/` at compile time, discovers all `.md` files with
//! frontmatter (`---` delimiters), and generates `src/docs_generated.rs`
//! containing `include_str!` entries for each discovered file.

use std::fs;
use std::io::{BufRead, BufReader};
use std::path::Path;

fn main() {
    let docs_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs");
    let docs_dir = docs_dir.canonicalize().expect("docs/ directory must exist");

    let out_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/docs_generated.rs");

    let mut entries: Vec<String> = Vec::new();

    collect_md_files(&docs_dir, &mut entries);

    let code = format!(
        "// Auto-generated by build.rs \u{2014} do not edit manually.\n\
         pub static SOURCES: &[&str] = &[\n{}\n];\n",
        entries.join("\n")
    );

    fs::write(&out_path, code).expect("failed to write docs_generated.rs");

    // Tell Cargo to re-run if docs change.
    println!("cargo:rerun-if-changed={}", docs_dir.display());
    rerun_if_changed_recursive(&docs_dir);
}

/// Recursively collect `.md` files whose first line is `---` (has frontmatter).
fn collect_md_files(dir: &Path, out: &mut Vec<String>) {
    let mut paths: Vec<_> = fs::read_dir(dir)
        .expect("failed to read docs dir")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .collect();

    // Sort for deterministic output.
    paths.sort();

    for path in paths {
        if path.is_dir() {
            collect_md_files(&path, out);
        } else if path.extension().map_or(false, |e| e == "md") {
            if has_frontmatter(&path) {
                out.push(format!(
                    "    include_str!(\"../../../{}\"),",
                    rel_from_repo(&path)
                ));
            }
        }
    }
}

/// Check whether a file starts with `---`.
fn has_frontmatter(path: &Path) -> bool {
    if let Ok(f) = fs::File::open(path) {
        let reader = BufReader::new(f);
        if let Some(Ok(line)) = reader.lines().next() {
            return line.trim() == "---";
        }
    }
    false
}

/// Get the path relative to the repo root (two levels up from CARGO_MANIFEST_DIR).
fn rel_from_repo(path: &Path) -> String {
    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../")
        .canonicalize()
        .unwrap();
    path.strip_prefix(&repo_root)
        .expect("path must be relative to repo root")
        .display()
        .to_string()
}

/// Register re-run triggers for every file in the docs tree.
fn rerun_if_changed_recursive(dir: &Path) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let p = entry.path();
            println!("cargo:rerun-if-changed={}", p.display());
            if p.is_dir() {
                rerun_if_changed_recursive(&p);
            }
        }
    }
}
